### ISSUE TITLE
Throws errors function calls are not supported while updating to angular 2.4.3

### ISSUE THREAD

**Issue by ashish173** [ngrx/store-log-monitor#23]
I updated to angular 2.4.3 latest stable and I am getting errors related to.

```
ERROR in Error encountered resolving symbol values statically. Calling function 'StoreDevtoolsModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function
```

IMO its mostly this code which is causing the problem.
```
StoreDevtoolsModule.instrumentStore({
  monitor: useLogMonitor({
     visible: false,
     position: 'right'
   })
})
```

@brandonroberts @robwormald & @MikeRyan52

**Comment by brandonroberts** [comment]
You should use the extension instead. See here for instructions: https://github.com/ngrx/store-devtools#instrumentation-with-the-chrome-extension-preferred
