### ISSUE TITLE
Unsupported for ngrx v4.x

### ISSUE THREAD

**Issue by hyndsite** [ngrx/store-log-monitor#30]
the NGRX v4.x migration guide recommends removing @ngrx/core which apparently the @ngrx/store-log-monitor is still using.

Can you confirm that there isn't support for this library in ngrx 4.x?

**Comment by REPTILEHAUS** [comment]
Did you get any insight into this.. im updating an NG2 repo and running into issues

**Comment by brandonroberts** [comment]
That is correct. You should migrate to https://github.com/ngrx/store-devtools to V4
