### ISSUE TITLE
docs/deps: typings not mentioned as global prerequisite nor local dependency

### ISSUE THREAD

**Issue by BrainCrumbz** [ngrx/store-log-monitor#5]
When trying to setup this project for first time build, CONTRIBUTING.md mentions to run `typings install` after `npm install`. Only to find that typings command could not be found.

It'd more helpful to contributors if typings was mentioned as a prerequisite to be globally installed or, as an (preferred?) alternative, was listed under package.json dependencies.

**Comment by BrainCrumbz** [comment]
Actually, it looks like typings.json is not there at all, so maybe contributing instructions need an update.

**Comment by MikeRyanDev** [comment]
Yeah, CONTRIBUTING.md is out of date.

**Comment by BrainCrumbz** [comment]
Finding out now, also about that "clean" script or something similar.
